version: 0.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alpha'
build:
  project: Cinegy.TsAnalysis.sln
  publish_nuget: true
  verbosity: minimal
before_build:
- cmd: nuget restore
after_build:
- cmd: >-
    7z a Cinegy.TsAnalysis-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.TsAnalysis\bin\release\Cinegy.TsAnalysis.dll

    appveyor PushArtifact Cinegy.TsAnalysis-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip

    7z a Cinegy.TsAnalysis-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.TsAnalysis\bin\release

    appveyor PushArtifact Cinegy.TsAnalysis-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
deploy:
- provider: NuGet
  api_key:
    secure: 6+9hzV1Up8Nxx2U/zVJk7TP85IoxlmNw9puov4SjaVaSNKMBNUbEiA4MOQkbiwrh
  skip_symbols: true
